const path = require('path');
const loaderUtils = require('loader-utils');
const apiPath = path.join(__dirname, 'api.js');

module.exports = function() {
  const { activationUrl, ips } = loaderUtils.getOptions(this) || {};

  return `
//############################ NOTICE ############################//
//                                                                //
//           This is a placeholder module generated by            //
//                 lazy-compile-webpack-plugin.                   //
//     https://github.com/liximomo/lazy-compile-webpack-plugin    //
//                                                                //
//    The real content is in the corresponding hot-update file.   //
//           You won't see this after the page refresh.           //
//                                                                //
//################################################################//

// @activationUrl ${activationUrl}

// modified from https://matthewrayfield.com/articles/animating-urls-with-javascript-and-emojis
var api = require('!!${apiPath}');
var stopAnimation = api.startAnimation();
var compilation = api.compile(${JSON.stringify(ips)}, '${activationUrl}');

window.onbeforeunload = function() {
  stopAnimation();
}
`.trim();
};
